version: '2'
services:
    databases:
        image: mysql
        ports:
        - "3306:3306"
        environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=rakesh
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=demodb
    web:
      image: nginx
